# Generated by Django 5.1.6 on 2025-06-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_delete_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('Machine_ID', models.CharField(help_text='Unique machine identifier', max_length=50, primary_key=True, serialize=False)),
                ('Machine_Name', models.CharField(help_text='Descriptive name of the equipment', max_length=200)),
                ('Machine_Type', models.CharField(choices=[('cnc_machine', 'CNC Machine'), ('press', 'Press'), ('conveyor', 'Conveyor System'), ('scale', 'Scale/Balance'), ('gauge', 'Measurement Gauge'), ('torque_wrench', 'Torque Wrench'), ('test_equipment', 'Test Equipment'), ('packaging', 'Packaging Equipment'), ('other', 'Other')], help_text='Type/category of equipment', max_length=50)),
                ('Machine_Location', models.CharField(help_text='Physical location of the equipment', max_length=200)),
                ('Last_Calibration_Date', models.DateField(blank=True, help_text='Date of last calibration', null=True)),
                ('Last_Maintenance_Date', models.DateField(blank=True, help_text='Date of last maintenance', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('calibration', 'Under Calibration'), ('inactive', 'Inactive'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('manufacturer', models.CharField(blank=True, help_text='Equipment manufacturer', max_length=100)),
                ('model_number', models.CharField(blank=True, help_text='Model/serial number', max_length=100)),
                ('installation_date', models.DateField(blank=True, help_text='Date equipment was installed', null=True)),
                ('maintenance_interval', models.PositiveIntegerField(default=90, help_text='Days between maintenance (default: 90)')),
                ('calibration_interval', models.PositiveIntegerField(default=365, help_text='Days between calibration (default: 365)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_created', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['Machine_ID'],
            },
        ),
    ]
