# Generated by Django 4.2.23 on 2025-08-15 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('maintenance', 'Maintenance/Calibration User'), ('quality', 'Quality Engineer')], default='maintenance', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('machine_id', models.CharField(help_text='Unique machine identifier', max_length=50, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(help_text='Name/description of the machine', max_length=200)),
                ('machine_type', models.CharField(choices=[('PRODUCTION', 'Production Equipment'), ('TESTING', 'Testing Equipment'), ('PACKAGING', 'Packaging Equipment'), ('CALIBRATION', 'Calibration Equipment'), ('OTHER', 'Other')], default='PRODUCTION', max_length=20)),
                ('machine_location', models.CharField(help_text='Physical location of the machine', max_length=200)),
                ('last_calibration_date', models.DateField(blank=True, help_text='Date of last calibration', null=True)),
                ('last_maintenance_date', models.DateField(blank=True, help_text='Date of last maintenance', null=True)),
                ('calibration_interval_days', models.IntegerField(default=365, help_text='Days between calibrations')),
                ('maintenance_interval_days', models.IntegerField(default=90, help_text='Days between maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['machine_name'],
            },
        ),
    ]
