# Generated by Django 4.2.23 on 2025-11-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('administrator', 'Administrator'), ('maintenance', 'Maintenance/Calibration User'), ('quality', 'Quality Engineer')], default='', max_length=20, null=True),
        ),
    ]
